<?php //áéíóú campos
$camposcepal=array(
	'id'=>array('tit'=>'id','txt'=>$row['id'],'edit'=>"<span class='link'><a onclick='editData(\"cepal\",\"".$row['id']."\")'>Editar</a></span>",'ficha'=>"<span><a class='a' href='files/ficha.php?num=$row[id]'>Ver Ficha</a></span>"),
	'4'=>array('tit'=>'tipo','txt'=>$row[4]),
	'122'=>array('tit'=>'catalogo','txt'=>$row[122]),
	'3'=>array('tit'=>'cod-inca','txt'=>"(Cod:".str_replace(' | ','',$row[3]).")"),
	'210'=>array('tit'=>'cod-web','txt'=>$row[210]),
	'120'=>array('tit'=>'promocion','txt'=>$row[120]),
	'10'=>array('tit'=>'autor(a)','txt'=>explode(' | ',$row[10])),
	'11'=>array('tit'=>'autor.instit(a)','txt'=>($row[11]?str_replace(' | ','. ',$row[11]).". ":$row[11])),
	'12'=>array('tit'=>'titulo(a)','txt'=>($row[12]?"<b style=$_3D'text-transform:uppercase;'>".preg_replace(array('/^</','/=.*>|>/','/ \| /'),array('','','. '),($row[12]))."</b>. ":$row[12])),
	'16'=>array('tit'=>'autor(m)','txt'=>explode(' | ',$row[16])),
	'17'=>array('tit'=>'autor.instit(m)','txt'=>($row[17]?str_replace(' | ','. ',$row[17]).". ":$row[17])),
	'18'=>array('tit'=>'titulo(m)','txt'=>($row[18]?"<b style=$_3D'text-transform:uppercase;'>".preg_replace(array('/^</','/=.*>|>/','/ \| /'),array('','','. '),($row[18]))."</b>. ":$row[18])),
	'21'=>array('tit'=>'no.volumen','txt'=>($row[21]?"<b>No. $row[21]</b>. ":$row[21])),
	'25'=>array('tit'=>'coleccion','txt'=>($row[25]?"<u>".str_replace(' | ','. ',$row[25])."</u>. ":$row[25])),
	'27'=>array('tit'=>'tot.vols','txt'=>($row[27]?"<u>No. $row[27]</u>. ":$row[27])),
	'47'=>array('tit'=>'isbn','txt'=>($row[47]?"ISBN: ".str_replace(' | ','. ',$row[47]).". ":$row[47])),
	'29'=>array('tit'=>'autor.instit(s)','txt'=>($row[29]?str_replace(' | ','. ',$row[29]).". ":$row[29])),
	'30'=>array('tit'=>'titulo(s)','txt'=>($row[30]?"<b style=$_3D'text-transform:uppercase;'>".preg_replace(array('/^</','/=.*>|>/','/ \| /'),array('','','. '),($row[30]))."</b>. ":$row[30])),
	'31'=>array('tit'=>'volumen(s)','txt'=>($row[31]?"<b>$row[31]</b>. ":$row[31])),
	'32'=>array('tit'=>'numero(s)','txt'=>($row[32]?"<b>No. $row[32]</b>. ":$row[32])),
	'35'=>array('tit'=>'issn','txt'=>($row[35]?"ISSN:$row[35]. ":$row[35])),
	'20'=>array('tit'=>'paginas','txt'=>($row[20]?"$row[20]p. ":$row[20])),
	'38'=>array('tit'=>'editorial','txt'=>($row[38]?str_replace(' | ','. ',$row[38]).". ":$row[38])),
	'39'=>array('tit'=>'ciudad','txt'=>($row[39]?"$row[39]. ":$row[39])),
	'40'=>array('tit'=>'pais','txt'=>($row[40]?"$row[40]. ":$row[40])),
	'41'=>array('tit'=>'edicion','txt'=>($row[41]?"$row[41]. ":$row[41])),
	'42'=>array('tit'=>'info.desc','txt'=>($row[42]?"$row[42]. ":$row[42])),
	'43'=>array('tit'=>'fecha.pub','txt'=>($row[43]?"$row[43]. ":$row[43])),
	'44'=>array('tit'=>'fecha(iso)','txt'=>($row[44]?"$row[44]. ":$row[44])),
	'63'=>array('tit'=>'impresion','txt'=>($row[63]?"$row[63]. ":$row[63])),
	'64'=>array('tit'=>'idioma','txt'=>($row[64]?"$row[64]. ":$row[64])),
	'68'=>array('tit'=>'notas','txt'=>($row[68]?"<i>$row[68]</i>. ":$row[68])),
	'71'=>array('tit'=>'resumen-catalogo','txt'=>($row[71]?"<i>$row[71]</i>. ":$row[71])),
	'72'=>array('tit'=>'resumen-tabla cont','txt'=>($row[72]?"<i>$row[72]</i>. ":$row[72])),
	'73'=>array('tit'=>'ref.bibliografia','txt'=>($row[73]?"$row[73]. ":$row[73])),
	'76'=>array('tit'=>'descriptores','txt'=>($row[76]?"<b style=$_3D'font-size:8pt;text-transform:uppercase;'>//".str_replace(' | ','. ',$row[76])."</b>. ":$row[76])),
	'80'=>array('tit'=>'materia','txt'=>($row[80]?"$row[80]. ":$row[80])),
	'82'=>array('tit'=>'cat.geografica','txt'=>($row[82]?"$row[82]. ":$row[82])),
	'48'=>array('tit'=>'en oferta','txt'=>($row[48]?"$row[48]. ":$row[48])),
	'102'=>array('tit'=>'precio compra','txt'=>($row[102]?"$row[102]. ":$row[102])),
	'103'=>array('tit'=>'precio venta','txt'=>($row[103]?"$row[103]. ":$row[103])),
	'108'=>array('tit'=>'fecha compra','txt'=>($row[108]?"$row[108]. ":$row[108])),
	'110'=>array('tit'=>'formato','txt'=>($row[110]?"$row[110]. ":$row[110])),
	'111'=>array('tit'=>'medidas','txt'=>($row[111]?"($row[111]). ":$row[111])),
	'114'=>array('tit'=>'stock','txt'=>($row[114]?"$row[114]. ":$row[114])),
	'115'=>array('tit'=>'por comprar','txt'=>($row[115]?"$row[115]. ":$row[115])),
	'123'=>array('tit'=>'barcode','txt'=>($row[123]?"$row[123]. ":$row[123])),
	'91'=>array('tit'=>'docum.resp','txt'=>($row[91]?str_replace(' | ','. ',$row[91]).". ":$row[91])),
	'999'=>array('tit'=>'imagen','txt'=>$row[999]),
);
?>